CREATE DATABASE SHIZA112;
use SHIZA112;
---SELECT
SELECT 'SHAZ'as Name,'22'as age ,'BBA'as qualification,'karachi'as  city;
---CREATE Table
CREATE TABLE EMPLOYEE(
ID INT,
NAME VARCHAR(50),
AGE INT, SALARY VARCHAR(100)
);
---SELECT
SELECT *FROM EMPLOYEE;
---INSERT
INSERT INTO EMPLOYEE VALUES
(1,'SIDRA',27,20000),
(2,'TOOBA',28,30000),
(3,'MARIUM',26,40000),
(4,'HAMNA',20,50000),
(5,'HIRA',21,60000),
(6,'ARFA',22,70000),
(7,'SHIZA',25,80000);
SELECT*FROM EMPLOYEE;
---ALTER
ALTER TABLE EMPLOYEE ADD SALARY VARCHAR(50);
---UPDATE EMPLOYEE
UPDATE EMPLOYEE SET SALARY='20000'
WHERE ID=1;
UPDATE EMPLOYEE SET SALARY='30000'
WHERE ID=2;
UPDATE EMPLOYEE SET SALARY='40000'
WHERE ID=3;
UPDATE EMPLOYEE SET SALARY='50000'
WHERE ID=4;
UPDATE EMPLOYEE SET SALARY='60000'
WHERE ID=5;
UPDATE EMPLOYEE SET SALARY='70000'
WHERE ID=6;
UPDATE EMPLOYEE SET SALARY='80000'
WHERE ID=7;
---TRUNCATE
TRUNCATE TABLE EMPLOYEE;
SELECT*FROM EMPLOYEE
---DELETE
DELETE FROM EMPLOYEE WHERE ID =3;
SELECT*FROM EPLOYEE
---DROP
DROP TABLE EMPLOYEE
SELECT*FROM EMPLOYEE;

------------------------------------CLASS #01 END-------------------------------------------